services:
  orderbookexecution.api:
    image: orderbookexecution.api
    platform: linux/amd64
    build:
      context: .
      dockerfile: OrderBookExecution.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DataSource:FilePath: "data/order_books_data"
